apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8-demo
spec:
  replicas: 3
  template:
    metadata:
      name: k8-demo
      labels:
        app: k8-demo
    spec:
      containers:
      - image: luksa/kubia:v1
        name: nodejs
        resources:
          requests:
            cpu: 100m
